# Site settings
title: Frisinacho's Blog
email: frisinacho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal web page.<br>
  Powered by Jekyll and hosted in GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frisinacho.github.io" # the base hostname & protocol for your site
twitter_username: frisinacho
github_username:  frisinacho

# Build settings
markdown: kramdown
timezone: Europe/Madrid
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Nacho"
